version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: devgotchi-postgres
    restart: always
    environment:
      POSTGRES_USER: devgotchi
      POSTGRES_PASSWORD: devgotchipassword
      POSTGRES_DB: devgotchi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: